[package]
name = "soma"
version = "0.1.0"
authors = ["Yechan Bae <qwazpia@gmail.com>", "Kangsu Kim <pica744@gmail.com>"]
edition = "2018"


[dependencies]
bollard = "0.1"
clap = "2.32.0"
crossterm = "0.5.0"
failure = "0.1.3"
futures = "0.1.25"
hyper = "0.12"
tokio = "0.1"

[lib]
name = "soma"
path = "src/lib.rs"

[[bin]]
name = "soma"
path = "src/main.rs"
doc = false
