[package]
name = "soma"
version = "0.1.0"
authors = ["Yechan Bae <qwazpia@gmail.com>", "Kangsu Kim <pica744@gmail.com>"]
edition = "2018"


[dependencies]
clap = "2.32.0"
futures = "0.1.25"
http = "0.1"
lazy_static = "1.2.0"
shiplift = { version = "0.4.0", default-features = false }
tokio = "0.1"

[lib]
name = "soma"
path = "src/lib.rs"

[[bin]]
name = "soma"
path = "src/main.rs"
