[package]
name = "soma"
version = "0.1.0"
authors = ["Yechan Bae <qwazpia@gmail.com>", "Kangsu Kim <pica744@gmail.com>"]
edition = "2018"


[dependencies]
bollard = "0.1"
clap = "2.32.0"
crossterm = "0.5.0"
dirs = "1.0.4"
failure = "0.1.3"
futures = "0.1.25"
fs2 = "0.4.3"
fs_extra = "1.1"
git2 = "0.8"
handlebars = "1.1"
hyper = "0.12"
serde = "1.0"
serde_cbor = "0.9.0"
serde_derive = "1.0"
tempfile = "3"
tokio = "0.1"
toml = "0.4"
question = "0.2"
whoami = "0.2"

[lib]
name = "soma"
path = "src/lib.rs"

[[bin]]
name = "soma"
test = false
doc = false
