[package]
name = "soma"
version = "0.1.0"
authors = ["Yechan Bae <qwazpia@gmail.com>", "Kangsu Kim <pica744@gmail.com>"]
edition = "2018"


[dependencies]
bollard = "0.1"
clap = "2.32.0"
crossterm = "0.5.0"
failure = "0.1.3"
futures = "0.1.25"
hyper = "0.12"
serde = "1.0"
serde_derive = "1.0"
tokio = "0.1"
toml = "0.4"

[lib]
name = "soma"
path = "src/lib.rs"

[[bin]]
name = "soma"
test = false
doc = false
