steps:
- script: cargo build
  displayName: 'Build'

- ${{ if eq(parameters.os, 'Windows') }}:
  - script: |
      START /B .ci\dockerd.exe --experimental
      cargo test -- --test-threads=1
    displayName: 'Test'
    env:
      - RUST_BACKTRACE: 1

- ${{ if ne(parameters.os, 'Windows') }}:
  - script: cargo test
    displayName: 'Test'
    env:
      - RUST_BACKTRACE: 1
